import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import { css } from '@emotion/react'

import Button from '../components/Button'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const [products, setProducts] = useState<
  //   { id: string; properties: { id: string }[] }[]
  // >([])

  const [products, setProducts] = useState<
    { id: string; name: string; createdAt: string }[]
  >([])
  // 주어진 데이터에서 어떤 데이터들을 표시할 것인가?
  // useEffect(() => {
  //   fetch('/api/get-dnfts')
  //     .then((res) => res.json())
  //     .then((data) => setProducts(data.dnfts))
  // }, [])

  // prisma
  useEffect(() => {
    fetch('/api/get-products')
      .then((res) => res.json())
      .then((data) => setProducts(data.dnfts))
    // res.status(200).json({ dnfts: products, message: 'Success' }) (이 부분을 맞춰줘야 한다.)
  }, [])
  // prisma

  const inputRef = useRef<HTMLInputElement>(null)

  const handleClick = () => {
    if (inputRef.current == null || inputRef.current.value === '') {
      alert('name을 넣어주세요.')
      return
    }
    fetch(`/api/add-dnft?name=${inputRef.current.value}`)
      .then((res) => res.json())
      .then((data) => alert(data.message))
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <input
          className="placeholder:italic placeholder:text-slate-400 block bg-white w-50 border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
          ref={inputRef}
          type="text"
          placeholder="name"
        />
        <button
          css={css`
            background-color: hotpink;
            padding: 16px;
            border-radius: 8px;
          `}
          onClick={handleClick}
        >
          Add DNFT
        </button>

        <Button onClick={handleClick}>ADD</Button>

        <div>
          <p>DNFT List</p>

          {/* prisma */}
          {products &&
            products.map((dnfts) => (
              <div key={dnfts.id}>
                {dnfts.name}
                <span>{dnfts.createdAt}</span>
              </div>
              //<div key = {item.id}>{item.name}</div>
            ))}

          {/* notion */}
          {/* {products &&
            products.map((dnft) => (
              <div key={dnft.id}>
                {JSON.stringify(dnft)}
                {dnft.properties &&
                  Object.entries(dnft.properties).map(([key, value]) => (
                    <button
                      key={key}
                      onClick={() => {
                        fetch(
                          `/api/get-detail?pageId=${dnft.id}&propertyId=${value.id}`
                        )
                          .then((res) => res.json())
                          .then((data) => alert(JSON.stringify(data.detail)))
                      }}
                    >
                      {key}
                    </button>
                  ))}
                <br />
                <br />
              </div>
            ))}
          div로 return */}
        </div>
      </main>
    </>
  )
}
